# Generated by Django 4.0.3 on 2022-04-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_lokalu', models.IntegerField()),
                ('powierzchnia', models.IntegerField()),
                ('kubatura', models.IntegerField()),
            ],
            options={
                'ordering': ('-numer_lokalu',),
            },
        ),
        migrations.CreateModel(
            name='Lokator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=30)),
                ('imie', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='MediaRozliczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_fv', models.CharField(max_length=5)),
                ('media_typ', models.CharField(max_length=5)),
                ('zuzycie', models.CharField(max_length=5)),
                ('data_wyst', models.DateTimeField(auto_now=True)),
                ('do_zaplaty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_jedn_np_fv', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('-data_wyst',),
            },
        ),
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_umowy', models.IntegerField()),
                ('data_zawarcia', models.DateTimeField(auto_now=True)),
                ('czynsz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ilosc_osob', models.IntegerField()),
                ('lokal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='najemnik.lokal')),
                ('lokator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='najemnik.lokator')),
            ],
            options={
                'ordering': ('-nr_umowy',),
            },
        ),
        migrations.CreateModel(
            name='Naliczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_naliczenia', models.DateTimeField()),
                ('czynsz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cieplo_koszt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cieplo_zuzycie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woda_koszt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('woda_zuzycie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odpady', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ilosc_osob', models.IntegerField()),
                ('naleznosc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_stan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kwota_wplywu_nalez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_wplywu_nalez', models.DateTimeField()),
                ('data_wpisu', models.DateTimeField(auto_now=True)),
                ('nr_umowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='najemnik.umowa')),
            ],
            options={
                'ordering': ('-data_wpisu',),
            },
        ),
        migrations.CreateModel(
            name='LicznikStan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_licznika', models.CharField(max_length=5)),
                ('nr_licznika', models.CharField(default='0', max_length=20)),
                ('stan_licznika', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_odczytu', models.DateTimeField(auto_now=True)),
                ('lokal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='najemnik.lokal')),
            ],
            options={
                'ordering': ('-data_odczytu',),
            },
        ),
    ]
