# Generated by Django 4.0.3 on 2022-04-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lokal',
            name='kubatura',
        ),
    ]
