# Generated by Django 4.0.3 on 2022-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0003_alter_lokal_options_alter_licznikstan_typ_licznika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licznikstan',
            name='nr_licznika',
            field=models.CharField(default='000000', max_length=20),
        ),
    ]
