# Generated by Django 4.0.3 on 2022-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0004_alter_licznikstan_nr_licznika'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licznikstan',
            options={'ordering': ('-data_odczytu',), 'verbose_name_plural': 'Stany Liczników'},
        ),
        migrations.AlterModelOptions(
            name='lokal',
            options={'ordering': ('numer_lokalu',), 'verbose_name_plural': 'Lokale'},
        ),
        migrations.AlterModelOptions(
            name='lokator',
            options={'ordering': ('nazwisko',), 'verbose_name_plural': 'Lokatorzy'},
        ),
        migrations.AlterModelOptions(
            name='mediarozliczenia',
            options={'ordering': ('-data_wyst',), 'verbose_name_plural': 'Rozliczenia'},
        ),
        migrations.AlterModelOptions(
            name='naliczenia',
            options={'ordering': ('-data_wpisu',), 'verbose_name_plural': 'Naliczenia'},
        ),
        migrations.AlterModelOptions(
            name='umowa',
            options={'ordering': ('-nr_umowy',), 'verbose_name_plural': 'Umowy'},
        ),
        migrations.AlterField(
            model_name='umowa',
            name='nr_umowy',
            field=models.CharField(max_length=10),
        ),
    ]
