# Generated by Django 4.0.3 on 2022-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0005_alter_licznikstan_options_alter_lokal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediarozliczenia',
            options={'ordering': ('-data_wyst',), 'verbose_name_plural': 'Rozliczenia z Dostawcami'},
        ),
        migrations.AlterField(
            model_name='licznikstan',
            name='typ_licznika',
            field=models.IntegerField(choices=[(1, 'Woda'), (2, 'Ciepło'), (3, 'Odpady')], default=1),
        ),
        migrations.AlterField(
            model_name='mediarozliczenia',
            name='media_typ',
            field=models.IntegerField(choices=[(1, 'Woda'), (2, 'Ciepło'), (3, 'Odpady')], default=1),
        ),
        migrations.AlterField(
            model_name='umowa',
            name='nr_umowy',
            field=models.CharField(max_length=15),
        ),
    ]
