# Generated by Django 4.0.3 on 2022-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0006_alter_mediarozliczenia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarozliczenia',
            name='zuzycie',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
