# Generated by Django 4.0.3 on 2022-04-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0007_alter_mediarozliczenia_zuzycie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokal',
            name='powierzchnia',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
