# Generated by Django 4.0.3 on 2022-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najemnik', '0008_alter_lokal_powierzchnia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokal',
            name='opis_lokalu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
